// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owldnjgrwlqmtsvygmsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bGRuamdyd2xxbXRzdnlnbXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjQ1OTMsImV4cCI6MjA2NzA0MDU5M30.hHspy-U6tRoEdJOTUj6gpsl7m0zwSkBF-WMaa8MEqZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});